version: '3.3'

services: 
    mongo:
        image: mongo
        environment: 
            - MONGO_INITDB_DATABASE=monitor
        ports: 
            - "27017:27017"

    redis:
      image: redis
      ports:
          - "6379:6379"

    feeder:
        build: ./feeder
        ports:
            - "3001:3001"

    app:
        build: ./app/app
        ports:
            - "3000:3000"
        environment: 
            - TWITTER_API_URL=http://feeder:3001
            - REPEAT_INTERVAL=5000
            - REDIS_PORT=6379
            - REDIS_HOST=redis
            - PERCENTAGE_WANTED=50
            - MONGO_DB_HOST=mongo
            - MONGO_DB_PORT=27017
            - MONGO_DB_DATABASE_NAME=monitor
            - WEBHOOK_ALERT_URL=https://webhook.site/853fe4e0-d545-46ad-8318-91e465c92d5d
